### ISSUE TITLE
Automate releases

### ISSUE THREAD

**Issue by michael-erasmus** [bufferapp/buda-protobufs#12]
It could be awesome to automate new releases, perhaps to both the Python and Node.js packages.

Right now we can create a python package `.tar.gz` file that can be uploaded manually as a release. We use the `VERSION` file to assign the version name in the `setup.py` file and the compressed package name.

So far I've also created new Node packages by manually publishing them to npm with `npm publish`. I've bumped the version manually in the `packages/node/package.json` file, and the Python and Node packages have different versions.

I can see it being useful to eventually have a full CI solution, but perhaps automating the process locally first would be a good first step?

Here is how I propose we could perhaps do it:

- We create a `make packages` command that will:
  - Build the Python and Node packages
  - Use the `VERSION` files to bump the version on both packages (not sure if it's feasible for the Node and Python packages to share a version number?)
 
- We create a `make publish` command that will:
  - Create a new release on Github with the correct version tag 
  - Upload the Python package `.tar.gz` to the release
  - Upload the Node package as a `.tar.gz` to the release (not sure if this is needed?)
  - Publish the npm package to npmjs
  - Publish the Python package to PyPI?

Would love your thoughts @davidgasquez and @djfarrelly! Definitely open to any other approaches too!

**Comment by davidgasquez** [comment]
Thanks for creating the issue @michael-erasmus, it does feel like something important to have in the near future to accelerate the development! Your approach makes sense and I'm up for starting to work on it! 😄 

> Use the VERSION files to bump the version on both packages (not sure if it's feasible for the Node and Python packages to share a version number?

It might be a good idea to have them in sync at least at the minor version so we know that we have the same schema. 

> Create a new release on Github with the correct version tag

I explored this option in the past but I didn't find anything to avoid having to get an authentication token. After another look, I think this might be really useful: https://github.com/github/hub/issues/1049! 

An alternative approach to avoid the publishing is moving the releases to GitHub repositories so we can install it from the repo but I think it'll be similar to this.

Ae there any other approach we might want to discuss?

**Comment by djfarrelly** [comment]
Great idea @michael-erasmus and great comments @davidgasquez! I'd love to do this on Travis or something. We can add npm credentials there and write a little js-wrapper or use `sed` or similar to automated the version in package.json if the tests pass and the build is on master - what do y'all think?

package.json
```
{
  "name": "@bufferapp/buda",
  "version": "__VERSION__",
...
```
npm-publish.sh
```
#!/bin/bash
VERSION=$(<VERSION)
sed -i 's/__VERSION__/$VERSION/' ./packages/node/package.json
cd /packages/node
npm publish
```

**Comment by davidgasquez** [comment]
Closing this one as we now have more specific places where we can discuss this:

- Automate NPN Releases (https://github.com/bufferapp/buda-protobufs/issues/17)
- Automate Python Releases (https://github.com/bufferapp/buda-protobufs/pull/18)
