### ISSUE TITLE
Add the url query parameter to visits

### ISSUE THREAD

**Issue by michael-erasmus** [bufferapp/buda-protobufs#14]
We do track some specific query parameters (`utm_` parameters), but it could be cool to add all parameters sent to the URL too.

This could maybe be implemented as a map:

```protobuf
map<string, string> query_params = 99;
```

**Comment by davidgasquez** [comment]
Good catch! If we can, we should aim to capture as much data as we're provided. 😄

**Comment by michael-erasmus** [comment]
Closing this one since we do send the raw query string and can model this in the pipeline from that.
