### ISSUE TITLE
Automate npm release

### ISSUE THREAD

**Issue by davidgasquez** [bufferapp/buda-protobufs#17]
Followup from https://github.com/bufferapp/buda-protobufs/issues/12. 

Would be awesome to also have `npm` automatically published with changes on `master`.

**Comment by djfarrelly** [comment]
@michael-erasmus @davidgasquez, I walked Harrison through this repo and buffer-js-buffermetrics and he mentioned Greenkeeper could be cool to help us out a bit: https://greenkeeper.io/#how-it-works
