### ISSUE TITLE
Only publish tagged commits

### ISSUE THREAD

**Issue by djfarrelly** [bufferapp/buda-protobufs#27]
### Idea
To minimize unnecessary publish commands run (which will fail due to duplicate packages), we could limit our `deploy`'s to using only tagged commits: https://docs.travis-ci.com/user/deployment/npm/#What-to-release

The workflow would be 
```
# Update the version file
echo "1.0.4" > VERSION
# Add the version commit
git commit -m "1.0.4"
# tag it
git tag 1.0.4
# push it and the tags
git push --tags
```
That could be pushed to master or to the branch then rebased into master.

What do you think @davidgasquez?

**Comment by davidgasquez** [comment]
Ups! Thanks for creating the issue @djfarrelly! I actually wanted to do this back in September (https://github.com/bufferapp/buda-protobufs/pull/18#issuecomment-327745680) but somehow forgot about it.
