### ISSUE TITLE
`product` or `application` field on signup events

### ISSUE THREAD

**Issue by michael-erasmus** [bufferapp/buda-protobufs#28]
After chatting with Tyler about starting to track Reply data in Buda, it seems like we might need to add an additional field to signup events to be able to filter on which product the signup happened (Publish or Reply, for now)

Once we do have a single signup service that all the multiple products can start using, we should hopefully be able to track this in one place, but it will probably still be useful to think about a user being able to 'signup'  for multiple products.

cc @djfarrelly Would love your thoughts on this as well!

**Comment by djfarrelly** [comment]
Great point @michael-erasmus! I'd say for this one `product` may feel more clear. In the future `application` or `platform` could be if we have different ways to sign up like Mobile or via some other flow.

I do think you raise a good question about having "multiple signups" for a single user if we can eventually track user signups across multiple products (granted we have a shared global user id). 

To track 2nd or 3rd product "signups" for existing users we could

1. Extend the signup model to be re-used for a single user (add an extra field like `is_original_signup` or similar) - We'd need to make sure people know that not all signups are the same. This could also be good as we would be able to segment the data by users that have previously signed up for other products and ones that have not.
2. Create a new event type like `NewAccount`/`NewUser` which supersedes our current `Signup` and is only triggered when a new account is created and the `Signup` event is then used for every specific product a user signs up for.
3. Something else I didn't think of 😉 

What do you think?

**Comment by michael-erasmus** [comment]
> Extend the signup model to be re-used for a single user (add an extra field like is_original_signup or similar)

Like this! Thinking this will only work once we have the shared global user id you mentioned, right? If we had this global id and can associate it with the signup event, we could also derive a field like `is_original_signup`, which would just be the first signup for that user.

> We'd need to make sure people know that not all signups are the same. This could also be good as we would be able to segment the data by users that have previously signed up for other products and ones that have not.

Yeah, totally agree. I think we'll probably have more of a need to be able to analyze things like multiple product usage for the same user in the near future! Right now, we could either model things explicitly such that the distinction is clear (like a Reply signups and Publish signups view in Looker), or keep a generic 'Signups' view that has a the `product` dimension you can filter on ([or both even](https://www.youtube.com/watch?v=vgk-lA12FBk)) 

> Create a new event type like NewAccount/NewUser which supersedes our current Signup and is only triggered when a new account is created and the Signup event is then used for every specific product a user signs up for.

Yeah, I think this could work well. If we can associate the NewAccount event with each subsequent Signup event with a global user id, it just becomes another 'funnel' for that user.

**Comment by michael-erasmus** [comment]
@djfarrelly for now does just adding the `product` field to the Protobuf and in Redshift/Looker feel like a good next step? 

Thinking that maybe we could then also set that as `'Publish'` from the existing signup tracking (and then if the Reply team can use this tracking they could also set that to `'Reply'`)

**Comment by michael-erasmus** [comment]
Also looping @mallen5311 into this one!
